# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js (14.15.0)
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'

      - name: Install Pacakges
        run: npm ci

      - name: Run tests
        env:
          CI: ""
        run: npm test

      - name: Build Step
        env:
          CI: ""
        run: npm run build

      - name: Deploy Storybook
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run deploy-storybook -- --ci

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}